services:
  - type: web
    name: backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: your_mongodb_url_here
    autoDeploy: true
    buildFilter:
      paths:
        - backend/**

  - type: static
    name: frontend
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    envVars:
      - key: REACT_APP_API_URL
        value: https://your-backend-service-name.onrender.com
    buildFilter:
      paths:
        - frontend/**
